In [67]:
import pandas as pd 
import numpy as np

In [68]:
file=pd.read_csv("C:/Users/grewa/Desktop/cervical_cancer/GSE208117_Processed_data_files_HeLa-HLA-G_VS._HeLa_FPKM.csv.gz")
id1=file['gene_id']
file

gene_id  Hela_1_FPKM  Hela_2_FPKM  Hela_3_FPKM  Hela_HLAG_4_FPKM  \
0         138241         6.86         6.54         7.25             10.74   
1           9374        23.69        25.44        26.50             34.41   
2         255762         0.53         0.24         0.54              0.23   
3           9074         0.03         0.13         0.07              0.00   
4          10599         0.32         0.27         0.33              0.43   
...          ...          ...          ...          ...               ...   
17835       1088         0.45         0.41         0.49              0.28   
17836     643155        20.00        20.34        20.33             42.62   
17837       4882         0.91         0.46         0.84              1.75   
17838      81689        39.01        39.72        38.08             31.20   
17839  107984562         1.45         1.54         1.26              0.77   

       Hela_HLAG_5_FPKM  Hela_HLAG_6_FPKM   gene_symbol  
0                 11.18             10.66       C9orf85  
1                 35.70             33.24          PPT2  
2                  0.44              0.49         PDZD9  
3                  0.00              0.00         CLDN6  
4                  0.39              0.37       SLCO1B1  
...                 ...               ...           ...  
17835              0.38              0.40       CEACAM8  
17836             39.56             40.46        SMIM15  
17837              2.09              2.11          NPR2  
17838             28.18             30.33         ISCA1  
17839              0.98              0.92  LOC107984562  

[17840 rows x 8 columns]

In [69]:
file.drop(['gene_id','gene_symbol'],axis=1,inplace=True)
file

Hela_1_FPKM  Hela_2_FPKM  Hela_3_FPKM  Hela_HLAG_4_FPKM  \
0             6.86         6.54         7.25             10.74   
1            23.69        25.44        26.50             34.41   
2             0.53         0.24         0.54              0.23   
3             0.03         0.13         0.07              0.00   
4             0.32         0.27         0.33              0.43   
...            ...          ...          ...               ...   
17835         0.45         0.41         0.49              0.28   
17836        20.00        20.34        20.33             42.62   
17837         0.91         0.46         0.84              1.75   
17838        39.01        39.72        38.08             31.20   
17839         1.45         1.54         1.26              0.77   

       Hela_HLAG_5_FPKM  Hela_HLAG_6_FPKM  
0                 11.18             10.66  
1                 35.70             33.24  
2                  0.44              0.49  
3                  0.00              0.00  
4                  0.39              0.37  
...                 ...               ...  
17835              0.38              0.40  
17836             39.56             40.46  
17837              2.09              2.11  
17838             28.18             30.33  
17839              0.98              0.92  

[17840 rows x 6 columns]

In [70]:
file=file.values
file

array([[ 6.86,  6.54,  7.25, 10.74, 11.18, 10.66],
       [23.69, 25.44, 26.5 , 34.41, 35.7 , 33.24],
       [ 0.53,  0.24,  0.54,  0.23,  0.44,  0.49],
       ...,
       [ 0.91,  0.46,  0.84,  1.75,  2.09,  2.11],
       [39.01, 39.72, 38.08, 31.2 , 28.18, 30.33],
       [ 1.45,  1.54,  1.26,  0.77,  0.98,  0.92]])

In [71]:
try:
    cpm=[]
    for i in range(0,len(file)):
            colsum=file[:,i].sum()

            c1=(file[:,i]/colsum)*10**6
            cpm.append(c1)
    
except:
    print("ignore error")
print(cpm)

ignore error
[array([15.15272232, 52.3276956 ,  1.17069137, ...,  2.010055  ,
       86.16730289,  3.20283489]), array([14.43494602, 56.15061573,  0.52972279, ...,  1.01530201,
       87.66912173,  3.39905457]), array([16.03283773, 58.60278618,  1.19416998, ...,  1.85759775,
       84.21109803,  2.78639663]), array([23.00522133, 73.7066728 ,  0.49266303, ...,  3.74852303,
       66.83081056,  1.64935013]), array([23.54981483, 75.19931927,  0.92682634, ...,  4.40242513,
       59.35901448,  2.06429504]), array([22.65642358, 70.64723451,  1.04143035, ...,  4.48452662,
       64.46241344,  1.95533862])]


In [72]:
cpm=np.array(cpm)
cpm

array([[15.15272232, 52.3276956 ,  1.17069137, ...,  2.010055  ,
        86.16730289,  3.20283489],
       [14.43494602, 56.15061573,  0.52972279, ...,  1.01530201,
        87.66912173,  3.39905457],
       [16.03283773, 58.60278618,  1.19416998, ...,  1.85759775,
        84.21109803,  2.78639663],
       [23.00522133, 73.7066728 ,  0.49266303, ...,  3.74852303,
        66.83081056,  1.64935013],
       [23.54981483, 75.19931927,  0.92682634, ...,  4.40242513,
        59.35901448,  2.06429504],
       [22.65642358, 70.64723451,  1.04143035, ...,  4.48452662,
        64.46241344,  1.95533862]])

In [73]:
logv=np.log2(cpm+1)
logv

array([[4.01370543, 5.73681308, 1.11815462, ..., 1.58978985, 6.44571517,
        2.07136278],
       [3.94812853, 5.83669714, 0.61327024, ..., 1.01099606, 6.47035988,
        2.1371935 ],
       [4.09024691, 5.89730787, 1.1336753 , ..., 1.51480285, 6.41296944,
        1.92082554],
       [4.58527633, 6.22316521, 0.57788851, ..., 2.24747885, 6.08386883,
        1.40563852],
       [4.61764024, 6.2517062 , 0.94622655, ..., 2.43360717, 5.91549735,
        1.61555521],
       [4.56416008, 6.16283911, 1.02958035, ..., 2.4553671 , 6.03259489,
        1.56332344]])

In [74]:
print("Minimum value:",logv[0].min(),"\nMaximmum value:",logv[0].max())

Minimum value: 0.0 
Maximmum value: 13.234660083796802


In [75]:
import scipy.stats as st
zscr=st.zscore(logv)
zscr

array([[-1.00104206, -1.39424827,  0.95052826, ..., -0.52946374,
         0.98386509,  1.04764218],
       [-1.22780567, -0.89913438, -1.28136808, ..., -1.60265521,
         1.09464256,  1.28902793],
       [-0.73636312, -0.59869388,  1.01913909, ..., -0.6685036 ,
         0.83667372,  0.49565753],
       [ 0.9754389 ,  1.01654387, -1.43777686, ...,  0.69001415,
        -0.6426266 , -1.39341209],
       [ 1.08735265,  1.15801836,  0.19050154, ...,  1.03513072,
        -1.39945288, -0.62369697],
       [ 0.9024193 ,  0.7175143 ,  0.55897605, ...,  1.07547768,
        -0.87310189, -0.81521857]])

In [76]:
zscr.shape

(6, 17840)

In [77]:
id1.values.shape

(17840,)

In [78]:
zscr=pd.DataFrame(zscr)
new=zscr.T
#new['gene']=id1
zscr=new.dropna()
#zscr['gene']=id1
zscr=zscr.values
zscr

array([[-1.00104206, -1.22780567, -0.73636312,  0.9754389 ,  1.08735265,
         0.9024193 ],
       [-1.39424827, -0.89913438, -0.59869388,  1.01654387,  1.15801836,
         0.7175143 ],
       [ 0.95052826, -1.28136808,  1.01913909, -1.43777686,  0.19050154,
         0.55897605],
       ...,
       [-0.52946374, -1.60265521, -0.6685036 ,  0.69001415,  1.03513072,
         1.07547768],
       [ 0.98386509,  1.09464256,  0.83667372, -0.6426266 , -1.39945288,
        -0.87310189],
       [ 1.04764218,  1.28902793,  0.49565753, -1.39341209, -0.62369697,
        -0.81521857]])

In [79]:
zscr[1:4]

array([[-1.39424827, -0.89913438, -0.59869388,  1.01654387,  1.15801836,
         0.7175143 ],
       [ 0.95052826, -1.28136808,  1.01913909, -1.43777686,  0.19050154,
         0.55897605],
       [-0.13348191,  1.8651035 ,  0.7140285 , -0.8152167 , -0.8152167 ,
        -0.8152167 ]])