In [14]:
import pandas as pd 
import numpy as np

In [15]:
file=pd.read_csv('C:/Users/grewa/Desktop/cervical_cancer/cervical_cancer.csv.gz')

In [16]:
file

Unnamed: 0  AAACCTGAGGACATTA-1  AAACGGGAGATGAGAG-1  \
0      ENSG00000243485                   0                   0   
1      ENSG00000237613                   0                   0   
2      ENSG00000186092                   0                   0   
3      ENSG00000238009                   0                   0   
4      ENSG00000239945                   0                   0   
...                ...                 ...                 ...   
33689  ENSG00000277856                   0                   0   
33690  ENSG00000275063                   0                   0   
33691  ENSG00000271254                   0                   0   
33692  ENSG00000277475                   0                   0   
33693  ENSG00000268674                   0                   0   

       AAACGGGCATAAGACA-1  AAACGGGGTCGAACAG-1  AAACGGGTCCAAACTG-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGATGAGGGTTCCC-1  AAAGCAAAGACAAAGG-1  AAAGCAAGTTTAAGCC-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGCAATCTGCCCTA-1  ...  TTTACTGCAATGGAGC-1  TTTACTGCAGATCCAT-1  \
0                       0  ...                   0                   0   
1                       0  ...                   0                   0   
2                       0  ...                   0                   0   
3                       0  ...                   0                   0   
4                       0  ...                   0                   0   
...                   ...  ...                 ...                 ...   
33689                   0  ...                   0                   0   
33690                   0  ...                   0                   0   
33691                   1  ...                   1                   1   
33692                   0  ...                   0                   0   
33693                   0  ...                   0                   0   

       TTTACTGGTAGGGACT-1  TTTACTGTCTACTCAT-1  TTTATGCAGGCCCTTG-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   1                   0      

In [17]:
file.drop(['Unnamed: 0'],axis=1,inplace=True)
file


AAACCTGAGGACATTA-1  AAACGGGAGATGAGAG-1  AAACGGGCATAAGACA-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAACGGGGTCGAACAG-1  AAACGGGTCCAAACTG-1  AAAGATGAGGGTTCCC-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGCAAAGACAAAGG-1  AAAGCAAGTTTAAGCC-1  AAAGCAATCTGCCCTA-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   1   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGTAGAGATCCGAG-1  ...  TTTACTGCAATGGAGC-1  TTTACTGCAGATCCAT-1  \
0                       0  ...                   0                   0   
1                       0  ...                   0                   0   
2                       0  ...                   0                   0   
3                       0  ...                   0                   0   
4                       0  ...                   0                   0   
...                   ...  ...                 ...                 ...   
33689                   0  ...                   0                   0   
33690                   0  ...                   0                   0   
33691                   0  ...                   1                   1   
33692                   0  ...                   0                   0   
33693                   0  ...                   0                   0   

       TTTACTGGTAGGGACT-1  TTTACTGTCTACTCAT-1  TTTATGCAGGCCCTTG-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691     

In [19]:
colo = file.columns
file

AAACCTGAGGACATTA-1  AAACGGGAGATGAGAG-1  AAACGGGCATAAGACA-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAACGGGGTCGAACAG-1  AAACGGGTCCAAACTG-1  AAAGATGAGGGTTCCC-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   0   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGCAAAGACAAAGG-1  AAAGCAAGTTTAAGCC-1  AAAGCAATCTGCCCTA-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691                   0                   0                   1   
33692                   0                   0                   0   
33693                   0                   0                   0   

       AAAGTAGAGATCCGAG-1  ...  TTTACTGCAATGGAGC-1  TTTACTGCAGATCCAT-1  \
0                       0  ...                   0                   0   
1                       0  ...                   0                   0   
2                       0  ...                   0                   0   
3                       0  ...                   0                   0   
4                       0  ...                   0                   0   
...                   ...  ...                 ...                 ...   
33689                   0  ...                   0                   0   
33690                   0  ...                   0                   0   
33691                   0  ...                   1                   1   
33692                   0  ...                   0                   0   
33693                   0  ...                   0                   0   

       TTTACTGGTAGGGACT-1  TTTACTGTCTACTCAT-1  TTTATGCAGGCCCTTG-1  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
33689                   0                   0                   0   
33690                   0                   0                   0   
33691     

In [20]:
file.sum()

AAACCTGAGGACATTA-1     78616
AAACGGGAGATGAGAG-1     30322
AAACGGGCATAAGACA-1     98255
AAACGGGGTCGAACAG-1     79178
AAACGGGTCCAAACTG-1     49456
                       ...  
TTTATGCCACGGATAG-1     44164
TTTATGCGTGACTCAT-1     73831
TTTCCTCTCCTCAACC-1    107530
TTTGCGCGTAAGAGAG-1     29536
TTTGTCAGTAAACACA-1     26617
Length: 884, dtype: int64

In [22]:
cpm = []
for i in range(0,len(file.columns)):
    tot = file.iloc[:,i].sum()
    count = (file.iloc[:,i]/tot)*10**6
    cpm.append(count)

In [23]:
cpm

[0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 33689    0.0
 33690    0.0
 33691    0.0
 33692    0.0
 33693    0.0
 Name: AAACCTGAGGACATTA-1, Length: 33694, dtype: float64,
 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 33689    0.0
 33690    0.0
 33691    0.0
 33692    0.0
 33693    0.0
 Name: AAACGGGAGATGAGAG-1, Length: 33694, dtype: float64,
 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 33689    0.0
 33690    0.0
 33691    0.0
 33692    0.0
 33693    0.0
 Name: AAACGGGCATAAGACA-1, Length: 33694, dtype: float64,
 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 33689    0.0
 33690    0.0
 33691    0.0
 33692    0.0
 33693    0.0
 Name: AAACGGGGTCGAACAG-1, Length: 33694, dtype: float64,
 0        0.0
 1        0.0
 2        0.0
 3        0.0
 4        0.0
         ... 
 33689    0.0
 33690    0.0
 33691    0.0
 33692    0.0
 33693    0.

In [24]:
cpm = np.array(cpm)
cpm

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., 18.59946062,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [25]:
logv=np.log2(cpm)
logv

C:\Users\grewa\AppData\Local\Temp\ipykernel_25880\2768767556.py:1: RuntimeWarning: divide by zero encountered in log2
  logv=np.log2(cpm)


array([[      -inf,       -inf,       -inf, ...,       -inf,       -inf,
              -inf],
       [      -inf,       -inf,       -inf, ...,       -inf,       -inf,
              -inf],
       [      -inf,       -inf,       -inf, ...,       -inf,       -inf,
              -inf],
       ...,
       [      -inf,       -inf,       -inf, ..., 4.21718888,       -inf,
              -inf],
       [      -inf,       -inf,       -inf, ...,       -inf,       -inf,
              -inf],
       [      -inf,       -inf,       -inf, ...,       -inf,       -inf,
              -inf]])

In [28]:
print("Minimum value:",logv[0].min(),"\nMaximmum value:",logv[0].max())

Minimum value: -inf 
Maximmum value: 15.042985884168084


In [30]:
import scipy.stats as st
z_score=st.zscore(logv)
z_score

c:\Users\grewa\miniconda3\lib\site-packages\numpy\core\_methods.py:233: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
c:\Users\grewa\miniconda3\lib\site-packages\scipy\stats\_stats_py.py:2897: RuntimeWarning: invalid value encountered in subtract
  z = (scores - mn) / std


array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [31]:
z_score.shape

(884, 33694)

In [41]:
z = pd.DataFrame(z_score).T
z = z.dropna(axis = 0)
z

0         1         2         3         4         5         6    \
59     1.380563 -0.981308  0.144767 -0.230008 -0.619873  0.614264 -1.362877   
72     0.412582 -3.520552 -1.364389 -0.052297  0.833154  0.003780  0.686849   
153   -0.916262 -0.060206  0.730133 -1.267467 -1.103637 -0.118097 -0.617514   
188   -0.041382  0.341750  0.418176 -1.010269  0.400165 -0.123077  0.399728   
197   -0.414256 -1.051272 -0.873368 -0.066839 -0.224686 -0.237532 -1.001749   
...         ...       ...       ...       ...       ...       ...       ...   
33659  1.013839  0.099389 -0.264686 -1.117913 -1.461174  0.290615  0.758039   
33660 -0.269096 -1.227191  0.859996  0.730577  0.755067  0.141887  1.095331   
33661  0.510224  1.835126  1.004911 -0.317895 -0.018600 -0.390373  1.423107   
33662  0.879594 -2.255170  0.635137  0.857797 -0.171792 -0.625538  0.489337   
33664  0.711303  0.963291  0.841055 -0.261514 -0.407335  0.219762  0.729045   

            7         8         9    ...       874       875       876  \
59     0.204592 -6.782868  0.443212  ...  0.477623  0.788994  0.646523   
72    -0.078137 -1.565101  0.756785  ... -0.485119  1.481734 -0.100947   
153    1.450931 -1.501961  1.098051  ... -0.389603  0.196211  0.465030   
188   -0.111750  0.236690 -0.283598  ... -0.998226  0.690879 -0.312605   
197    0.374609  0.038145  0.985255  ... -0.595813  0.331865 -0.302768   
...         ...       ...       ...  ...       ...       ...       ...   
33659  0.147927 -0.207728 -0.070000  ...  0.291573  0.497381  0.764721   
33660  0.604666 -0.677412 -0.014617  ... -1.687142  0.992769  0.405080   
33661 -0.191536 -0.534499 -0.286552  ...  0.657944 -0.651953 -0.243524   
33662 -0.425623 -0.613561 -0.936421  ... -0.388144  0.669705  0.077178   
33664 -0.350315 -1.479241 -0.199197  ...  0.403316 -0.334453  0.285555   

            877       878       879       880       881       882       883  
59    -0.266050  0.081123 -1.200516  1.531638 -0.580708  0.352797 -2.564479  
72     0.338234  0.457193 -0.761203  0.701588  0.038564  0.441169 -4.342880  
153   -0.192320 -0.811824 -1.252997 -0.777376  0.378636  0.544946 -5.022167  
188   -1.602243  0.684787 -0.674472  0.670627  0.174404  1.508478 -1.179257  
197   -0.227667 -0.515056  1.757032 -0.269301  0.897692  0.881250 -0.086377  
...         ...       ...       ...       ...       ...       ...       ...  
33659 -0.349017 -0.535314  1.043925  0.647805 -0.180262 -0.408087  5.294195  
33660  0.389158 -0.311025  0.109199 -1.321339 -0.620530 -0.040403  3.019972  
33661  0.333470 -0.167684  0.808868 -0.414683 -0.146950 -0.947342  5.238041  
33662  0.168633 -0.821035  0.836133  0.268933 -0.223345  0.417854  4.376295  
33664  0.265775 -0.148323  0.176483 -0.285029 -0.144430 -0.727603  5.680925  

[417 rows x 884 columns]

In [42]:
zsc = z.values


In [43]:
zsc

array([[ 1.38056269, -0.98130817,  0.14476708, ..., -0.58070786,
         0.35279654, -2.56447888],
       [ 0.41258243, -3.52055191, -1.36438934, ...,  0.03856366,
         0.44116925, -4.34288033],
       [-0.91626198, -0.06020616,  0.73013286, ...,  0.37863641,
         0.54494593, -5.02216718],
       ...,
       [ 0.51022442,  1.83512576,  1.00491112, ..., -0.14695038,
        -0.94734183,  5.23804124],
       [ 0.87959355, -2.25517045,  0.63513673, ..., -0.2233454 ,
         0.41785399,  4.37629474],
       [ 0.71130306,  0.96329073,  0.84105456, ..., -0.14442996,
        -0.72760331,  5.68092505]])

In [44]:
zsc[1:4]

array([[ 0.41258243, -3.52055191, -1.36438934, ...,  0.03856366,
         0.44116925, -4.34288033],
       [-0.91626198, -0.06020616,  0.73013286, ...,  0.37863641,
         0.54494593, -5.02216718],
       [-0.04138164,  0.34174968,  0.41817565, ...,  0.17440398,
         1.5084779 , -1.17925706]])